### ISSUE TITLE
Error: All providers failed

### ISSUE THREAD

**Issue by asdec** [Richienb/iplocation#22]
```
0|API      | Mon Sep 23 2019 07:54:43 GMT+0000 (UTC) { Error: All providers failed.
0|API      |     at new ProviderError (/home/ubuntu/api/node_modules/iplocation/lib/index.js:39:28)
0|API      |     at retry (/home/ubuntu/api/node_modules/iplocation/lib/index.js:55:29)
0|API      |     at Request._callback (/home/ubuntu/api/node_modules/iplocation/lib/index.js:65:28)
0|API      |     at Request.self.callback (/home/ubuntu/api/node_modules/iplocation/node_modules/request/request.js:185:22)
0|API      |     at emitTwo (events.js:126:13)
0|API      |     at Request.emit (events.js:214:7)
0|API      |     at Request.<anonymous> (/home/ubuntu/api/node_modules/iplocation/node_modules/request/request.js:1161:10)
0|API      |     at emitOne (events.js:116:13)
0|API      |     at Request.emit (events.js:211:7)
0|API      |     at IncomingMessage.<anonymous> (/home/ubuntu/api/node_modules/iplocation/node_modules/request/request.js:1083:12)
0|API      |     at Object.onceWrapper (events.js:313:30)
0|API      |     at emitNone (events.js:111:20)
0|API      |     at IncomingMessage.emit (events.js:208:7)
0|API      |     at IncomingMessage.wrapped (/home/ubuntu/api/node_modules/newrelic/lib/transaction/tracer/index.js:188:22)
0|API      |     at IncomingMessage.wrappedResponseEmit (/home/ubuntu/api/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:212:24)
0|API      |     at endReadableNT (_stream_readable.js:1064:12)
0|API      |     at Shim.applySegment (/home/ubuntu/api/node_modules/newrelic/lib/shim/shim.js:1424:20)
0|API      |     at wrapper (/home/ubuntu/api/node_modules/newrelic/lib/shim/shim.js:2065:17)
0|API      |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
0|API      |     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:218:9) message: 'All providers failed.' }
```

Getting this error on one server. Same works fine on other servers.

**Comment by fkgfahad** [comment]
same issue.

**Comment by A-Tokyo** [comment]
Note: This module has been deprecated on npm

I tried playing around with the code to add more providers but it was so much trouble.

I ended up using https://www.npmjs.com/package/geoip-lite on the backend and https://github.com/A-Tokyo/micro-geoip-lite on the frontend

**Comment by A-Tokyo** [comment]
Note: This module has been deprecated on npm

I tried playing around with the code to add more providers but it was a bit too much work to parse all the schemas from the different providers, also finding free ones became a bit harder overtime

I ended up using  https://github.com/A-Tokyo/micro-geoip-lite on the frontend which is an online micro service based wrapper of https://www.npmjs.com/package/geoip-lite


I will try to update this repo as well when I have more time to handle different schemas etc. :)

**Comment by Richienb** [comment]
Should be fixed now.
